apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snackager-config
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: snackager-config
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: production__snack__snackager__env
      version: "latest"

